#include "GPIO.h"
void GPIO_Init ()
{
	CONFIG_PIN_AS_GPIO(PTG,PTG0,OUTPUT);
	CONFIG_PIN_AS_GPIO(PTG ,PTG1,OUTPUT);
	CONFIG_PIN_AS_GPIO(PTG,PTG2,OUTPUT);
	CONFIG_PIN_AS_GPIO(PTC,PTC5,INPUT); /* Configure SW1 (PTD0) as an input */
	ENABLE_INPUT(PTC,PTC5);			 /* Enable input SW1*/
	OUTPUT_SET(PTG,PTG0);
  OUTPUT_SET(PTG,PTG1);
	OUTPUT_SET(PTG,PTG2);//¹Ø±Õ
}
